<?php

namespace Proxies\__CG__\BeWelcome\RoxBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Member extends \BeWelcome\RoxBundle\Entity\Member implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setUsername($username)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setLastName($lastName)
    {
        $this->__load();
        return parent::setLastName($lastName);
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function addSentMessage(\BeWelcome\RoxBundle\Entity\Message $sentMessages)
    {
        $this->__load();
        return parent::addSentMessage($sentMessages);
    }

    public function removeSentMessage(\BeWelcome\RoxBundle\Entity\Message $sentMessages)
    {
        $this->__load();
        return parent::removeSentMessage($sentMessages);
    }

    public function getSentMessages()
    {
        $this->__load();
        return parent::getSentMessages();
    }

    public function addReceivedMessage(\BeWelcome\RoxBundle\Entity\Message $receivedMessages)
    {
        $this->__load();
        return parent::addReceivedMessage($receivedMessages);
    }

    public function removeReceivedMessage(\BeWelcome\RoxBundle\Entity\Message $receivedMessages)
    {
        $this->__load();
        return parent::removeReceivedMessage($receivedMessages);
    }

    public function getReceivedMessages()
    {
        $this->__load();
        return parent::getReceivedMessages();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'username', 'email', 'firstName', 'lastName', 'status', 'sentMessages', 'receivedMessages');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}